import express from "express";
import path from "path";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

// Lazy initialization function for Google GenAI client to prevent startup crashes
let aiInstance: GoogleGenAI | null = null;
function getAI(): GoogleGenAI {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    aiInstance = new GoogleGenAI({ apiKey });
  }
  return aiInstance;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware to parse JSON bodies
  app.use(express.json());

  // 1. HEALTH CHECK ENDPOINT
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", time: new Date().toISOString() });
  });

  // 2. TEXT-TO-SPEECH (TTS) ENDPOINT
  // Uses the "gemini-3.1-flash-tts-preview" model as requested.
  app.post("/api/tts", async (req, res) => {
    try {
      const { text } = req.body;
      if (!text || typeof text !== "string") {
        res.status(400).json({ error: "Missing required text field" });
        return;
      }

      console.log(`Generating speech for: "${text.substring(0, 50)}..."`);
      const ai = getAI();

      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-tts-preview",
        contents: [{ parts: [{ text }] }],
        config: {
          responseModalities: ["AUDIO"],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: "Kore" }
            }
          }
        }
      });

      const parts = response.candidates?.[0]?.content?.parts;
      const audioPart = parts?.find(p => p.inlineData?.mimeType?.startsWith("audio/"));

      if (!audioPart || !audioPart.inlineData) {
        // Fallback or retry with general audio response type if specific tts-preview structure differs
        // Let's inspect if there are any other parts
        console.warn("No inline audio part found in response parts. Inspecting parts:", JSON.stringify(parts));
        res.status(500).json({ 
          error: "No audio generated by the model", 
          debugParts: parts 
        });
        return;
      }

      res.json({
        mimeType: audioPart.inlineData.mimeType,
        base64Data: audioPart.inlineData.data,
      });
    } catch (error: any) {
      const errMsg = error?.message || "";
      if (errMsg.includes("leaked") || errMsg.includes("API key") || errMsg.includes("PERMISSION_DENIED") || errMsg.includes("403")) {
        console.warn("TTS Service: Google Gemini API key is currently restricted or reported as leaked. Client will fall back to browser-native voice synthesis.");
        res.status(403).json({ 
          error: "API_KEY_RESTRICTED", 
          message: "The server Gemini API key is unavailable. Falling back to browser-native speech synthesis." 
        });
      } else {
        console.warn("TTS generation warning:", errMsg || error);
        res.status(500).json({ error: errMsg || "Failed to generate speech" });
      }
    }
  });

  // 3. GOOGLE FORMS PROXIES
  // Proxies requests to Google Forms API on behalf of the client using their OAuth access token.
  
  // Create a customized Intake Form for a Course
  app.post("/api/forms/create", async (req, res) => {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      res.status(401).json({ error: "Missing or invalid Authorization header" });
      return;
    }

    const { courseTitle, courseId } = req.body;
    if (!courseTitle || !courseId) {
      res.status(400).json({ error: "Missing courseTitle or courseId" });
      return;
    }

    const accessToken = authHeader.split(" ")[1];

    try {
      // Step A: Create the base Google Form
      console.log(`Creating Google Form for course: ${courseTitle}`);
      const createResponse = await fetch("https://forms.googleapis.com/v1/forms", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          info: {
            title: `Qalbiya Institute Intake – ${courseTitle}`,
            documentTitle: `${courseTitle} Registration Intake`
          }
        })
      });

      if (!createResponse.ok) {
        const errText = await createResponse.text();
        throw new Error(`Google Forms Create API failed: ${createResponse.status} - ${errText}`);
      }

      const formObj = await createResponse.json();
      const { formId, responderUri } = formObj;
      console.log(`Created form with ID: ${formId}, public URL: ${responderUri}`);

      // Step B: Add structural intake questions (Name, Age, Background, Motivation)
      const updateResponse = await fetch(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          requests: [
            {
              createItem: {
                item: {
                  title: "Full Name",
                  questionItem: {
                    question: {
                      required: true,
                      textQuestion: { paragraph: false }
                    }
                  }
                },
                location: { index: 0 }
              }
            },
            {
              createItem: {
                item: {
                  title: "Age / Age Group",
                  questionItem: {
                    question: {
                      required: true,
                      textQuestion: { paragraph: false }
                    }
                  }
                },
                location: { index: 1 }
              }
            },
            {
              createItem: {
                item: {
                  title: "Previous Islamic Studies or Quranic Reading Background",
                  questionItem: {
                    question: {
                      required: false,
                      textQuestion: { paragraph: true }
                    }
                  }
                },
                location: { index: 2 }
              }
            },
            {
              createItem: {
                item: {
                  title: "What are you hoping to achieve or learn from this course?",
                  questionItem: {
                    question: {
                      required: true,
                      textQuestion: { paragraph: true }
                    }
                  }
                },
                location: { index: 3 }
              }
            }
          ]
        })
      });

      if (!updateResponse.ok) {
        const errText = await updateResponse.text();
        throw new Error(`Google Forms Update API failed: ${updateResponse.status} - ${errText}`);
      }

      res.json({
        success: true,
        formId,
        formUrl: responderUri
      });
    } catch (error: any) {
      console.error("Google Form creation failed:", error);
      res.status(500).json({ error: error.message || "Failed to create intake form" });
    }
  });

  // Fetch responses for a given Form ID
  app.get("/api/forms/:formId/responses", async (req, res) => {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      res.status(401).json({ error: "Missing or invalid Authorization header" });
      return;
    }

    const { formId } = req.params;
    const accessToken = authHeader.split(" ")[1];

    try {
      console.log(`Fetching Google Form responses for ID: ${formId}`);
      
      // First, get the form structure to match questionIds with text questions
      const formDetailsResponse = await fetch(`https://forms.googleapis.com/v1/forms/${formId}`, {
        headers: { "Authorization": `Bearer ${accessToken}` }
      });

      let questionMap: Record<string, string> = {};
      if (formDetailsResponse.ok) {
        const formDetails = await formDetailsResponse.json();
        const items = formDetails.items || [];
        items.forEach((item: any) => {
          if (item.questionItem?.question) {
            questionMap[item.questionItem.question.questionId] = item.title;
          }
        });
      }

      // Second, get the responses
      const responsesResponse = await fetch(`https://forms.googleapis.com/v1/forms/${formId}/responses`, {
        headers: { "Authorization": `Bearer ${accessToken}` }
      });

      if (!responsesResponse.ok) {
        // If it returns 404 or something, maybe there are no responses yet or API has error
        if (responsesResponse.status === 404) {
          res.json({ responses: [], questionMap });
          return;
        }
        const errText = await responsesResponse.text();
        throw new Error(`Google Forms Responses API failed: ${responsesResponse.status} - ${errText}`);
      }

      const responseData = await responsesResponse.json();
      const responses = responseData.responses || [];

      // Process and structure responses nicely for easier visualization in client
      const structuredResponses = responses.map((resp: any) => {
        const answersList = Object.entries(resp.answers || {}).map(([questionId, ansObj]: [string, any]) => {
          const textAnswers = ansObj.textAnswers?.answers || [];
          const answerText = textAnswers.map((a: any) => a.value).join(", ");
          return {
            questionId,
            question: questionMap[questionId] || `Question (${questionId})`,
            answer: answerText
          };
        });

        return {
          responseId: resp.responseId,
          submittedAt: resp.createTime,
          answers: answersList
        };
      });

      res.json({
        responses: structuredResponses,
        questionMap
      });
    } catch (error: any) {
      console.error("Google Form response fetch failed:", error);
      res.status(500).json({ error: error.message || "Failed to fetch responses" });
    }
  });

  // 3.5. TRIGGER WELCOME EMAIL (CLOUD FUNCTION EMULATION)
  app.post("/api/trigger-welcome-email", async (req, res) => {
    try {
      const { uid, courseId, studentName, studentEmail, courseTitle, instructor, duration, schedule, description } = req.body;
      
      if (!uid || !courseId || !studentEmail || !courseTitle) {
        res.status(400).json({ error: "Missing required fields (uid, courseId, studentEmail, courseTitle)" });
        return;
      }

      console.log(`[Cloud Function Triggered] Generating welcome email for ${studentName || studentEmail} enrolled in ${courseTitle}...`);

      const ai = getAI();

      const prompt = `
You are the Chief Academic Officer at Qalbiya Islamic Institute. Write a highly personalized, warm, and professional "Welcome to the Course" email for a student who has successfully enrolled in our program.

Student Details:
- Name: ${studentName || "Respected Student"}
- Email: ${studentEmail}

Course Details:
- Title: ${courseTitle}
- Instructor: ${instructor || "Qualified Certified Instructor"}
- Duration: ${duration || "Varies"}
- Schedule: ${schedule || "Varies"}
- Description: ${description || ""}

Institute Context:
- Brand Name: Qalbiya Islamic Institute
- Aesthetic: Soft blush pink background, traditional, cohort-based, heart-centric, systematic learning, warm and prestigious feel.

Please structure the response as a JSON object containing two fields:
1. "subject": A compelling, warm email subject line.
2. "emailBody": A fully formatted, beautiful, responsive HTML email body. Use inline styles. Use a clean color palette (like deep green #22301F, gold accents #B0863A, warm backgrounds #FCF1F3, and clean dark gray #2B2A25 for text) to match Qalbiya's visual identity. Include an encouraging personal message, details of what to expect (the semester schedule, live cohorts, homework), a welcoming note from their instructor, and a sign-off. Ensure it is highly readable and mobile-friendly.

Do not output any markdown code blocks (like \`\`\`json) outside the JSON. Return strictly a raw valid JSON object.
`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json"
        }
      });

      const responseText = response.text || "";
      let parsed;
      try {
        parsed = JSON.parse(responseText.trim());
      } catch (jsonErr) {
        console.warn("Failed to parse direct JSON response from Gemini, cleaning markdown wrapper...", jsonErr);
        const cleaned = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
        parsed = JSON.parse(cleaned);
      }

      res.json({
        success: true,
        subject: parsed.subject || `Welcome to ${courseTitle} – Qalbiya`,
        emailBody: parsed.emailBody || `<p>Welcome to ${courseTitle}!</p>`,
      });
    } catch (error: any) {
      console.error("Welcome email generation error:", error);
      res.status(500).json({ error: error.message || "Failed to generate welcome email" });
    }
  });

  // 3.6. GENERATE KEY LEARNINGS DYNAMICALLY
  app.post("/api/key-learnings", async (req, res) => {
    try {
      const { courseId, courseTitle, description, instructor } = req.body;
      
      if (!courseId || !courseTitle) {
        res.status(400).json({ error: "Missing required fields (courseId, courseTitle)" });
        return;
      }

      console.log(`[Gemini API] Generating Key Learnings for course: ${courseTitle}`);
      
      let ai;
      try {
        ai = getAI();
      } catch (keyErr: any) {
        console.warn("Gemini Client Init Warning (Using fallback mock learnings):", keyErr.message);
        throw new Error("API_KEY_UNAVAILABLE");
      }

      const prompt = `
You are the Academic Director of Qalbiya Islamic Institute. Based on the course details below, generate a beautiful, inspiring, and concise "Key Learnings Summary" containing exactly 3 active bullet points. Each bullet point should explain exactly what practical skills, spiritual insights, or academic milestones the student will achieve by the end of the semester.

Please use your Google Search grounding tool to find accurate and up-to-date context, references, or general curriculum details related to this course if needed.

Course Details:
- Title: ${courseTitle}
- Description: ${description || "No description provided."}
- Instructor: ${instructor || "Qualified Certified Instructor"}

Please structure the response as a JSON object with:
{
  "learnings": [
    "First concrete, inspiring semester achievement starting with an active verb.",
    "Second concrete, inspiring semester achievement starting with an active verb.",
    "Third concrete, inspiring semester achievement starting with an active verb."
  ],
  "spiritualOutcome": "An inspiring 1-2 sentence closing statement about the deep heart-centric spiritual transformation or lasting benefit this course aims to instill by the end of the semester."
}

Do not output any markdown code blocks (like \`\`\`json) outside the JSON. Return strictly a raw valid JSON object.
`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          tools: [{ googleSearch: {} }]
        }
      });

      const responseText = response.text || "";
      let parsed;
      try {
        parsed = JSON.parse(responseText.trim());
      } catch (jsonErr) {
        console.warn("Failed to parse direct JSON response from Gemini, cleaning markdown wrapper...", jsonErr);
        const cleaned = responseText.replace(/```json/g, "").replace(/```/g, "").trim();
        parsed = JSON.parse(cleaned);
      }

      // Extract Grounding Search Sources
      const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
      const sources = chunks
        .map((c: any) => ({
          title: c.web?.title || c.web?.uri || "Google Search Verification Source",
          uri: c.web?.uri || ""
        }))
        .filter((s: any) => s.uri !== "");

      res.json({
        success: true,
        learnings: parsed.learnings || [],
        spiritualOutcome: parsed.spiritualOutcome || "",
        sources: sources
      });
    } catch (error: any) {
      console.warn("Key learnings generation caught error:", error.message || error);
      
      // Beautiful fallback data so the client always gets a high-quality, professional experience
      const fallbackLearnings: Record<string, { learnings: string[], spiritualOutcome: string }> = {
        "tajweed-basics": {
          learnings: [
            "Master the correct pronunciation (Makharij) and characteristics of Arabic letters.",
            "Apply fundamental Tajweed rules such as Noon Sakinah, Meem Sakinah, and Madd.",
            "Recite selected Surahs of Juz 'Amma with beautiful flow and enhanced confidence."
          ],
          spiritualOutcome: "Reconnect with the Divine words on a deeper level, finding internal tranquility through systematic and soulful recitation."
        },
        "arabic-basics": {
          learnings: [
            "Acquire standard vocabulary of over 150 daily Quranic Arabic words.",
            "Understand the basic syntax, noun declensions, and simple verb conjugations.",
            "Translate simple Quranic verses independently to connect directly during prayer."
          ],
          spiritualOutcome: "Unlock a key portal to the Divine text, beginning a lifelong journey of direct understanding and elevated concentration."
        },
        "islamic-history": {
          learnings: [
            "Analyze key moments in early Islamic history and the lives of the noble Companions.",
            "Extract timeless lessons of character, perseverance, and wisdom from classical events.",
            "Understand the historical preservation and cultural expansion of our rich heritage."
          ],
          spiritualOutcome: "Situate your personal identity within a grand legacy of courage, knowledge, and spiritual devotion."
        }
      };

      const titleKey = (req.body.courseTitle || "").toLowerCase();
      let matched = fallbackLearnings["tajweed-basics"];
      if (titleKey.includes("arabic")) {
        matched = fallbackLearnings["arabic-basics"];
      } else if (titleKey.includes("history") || titleKey.includes("seerah") || titleKey.includes("companion")) {
        matched = fallbackLearnings["islamic-history"];
      } else {
        // Dynamic generic fallback based on course title
        matched = {
          learnings: [
            `Develop a robust, structured foundation in ${req.body.courseTitle || 'your studies'} under expert guidance.`,
            "Translate academic, textual knowledge into practical, everyday spiritual habits.",
            "Participate in a supportive, cohort-based student environment designed for lifelong success."
          ],
          spiritualOutcome: `Attain closeness to Divine wisdom, aligning your mind and heart through sincere study and community connection.`
        };
      }

      res.json({
        success: true,
        isFallback: true,
        learnings: matched.learnings,
        spiritualOutcome: matched.spiritualOutcome,
        sources: []
      });
    }
  });

  // 4. VITE MIDDLEWARE SETUP FOR DEV/PRODUCTION
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Qalbiya Backend] Server running on http://localhost:${PORT}`);
  });
}

startServer();
